[credentials]
usernames = { transree = {failed_login_attempts = 0,  logged_in = false, name = "Trans Ree", password = "1234"}, rbriggs = {failed_login_attempts = 0,  logged_in = false, name = "R Briggs", password = "abc"}}

[cookie]
expiry_days = 1
key = "some_signature_key"  # Must be string
name = "some_cookie_name"